resources:

############################################
# The basics. used in all jobs.
############################################
  - name: hook-repo
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: trriplejay/fun-hooks
      branch: master

##############################################
# The hooks. one per job.
##############################################
  - name: translate
    type: webhook
    versionTemplate:
      webhookKey: tCv4fhCogSqmyjmRgvuR

  - name: warmup
    type: webhook
    versionTemplate:
      webhookKey: hAlQjJboj5ZALQENheQN


jobs:
  - name: execute-warmup
    type: runSh
    steps:
      - IN: warmup
      - IN: hook-repo
        switch: off
      - TASK:
          script:
            - sudo apt-get install libssl-dev
            - pushd $(shipctl get_resource_state hook-repo)
            - HOOK_META=$(shipctl get_resource_meta warmup)
            - ls $HOOK_META
            - cat $HOOK_META/version.json
            #- export response_url=$(shipctl get_resource_version_key warmup payload | jq '.response_url')

            - export response_url=$(shipctl get_json_value "$HOOK_META/version.json" "version.propertyBag.payload.response_url")
            - echo "$response_url"
            - sh respond.sh "engines online..."
    on_success:
      script:
        - echo "machine is warm"
    on_failure:
      script:
        - echo "something went wrong!"


  - name: execute-translate
    type: runSh
    steps:
      - IN: hook-repo
        switch: off
      - IN: translate
      - TASK:
          script:
            - echo "translating..."
            - RESULT=$(sh translate.sh)
            - sh respond.sh $RESULT
