mainTemplate: &mainTemplate
  - if [ $JOB_TRIGGERED_BY_NAME == "reset" ]; then echo "resetting job to failed state"; return 1; fi
  - HOOK_META=$(shipctl get_resource_meta $JOB_TRIGGERED_BY_NAME)
  - export response_url=$(shipctl get_json_value "$HOOK_META/version.json" "version.propertyBag.payload.response_url")
  - export message=$(shipctl get_json_value "$HOOK_META/version.json" "version.propertyBag.payload.text")
  - export user=$(shipctl get_json_value "$HOOK_META/version.json" "version.propertyBag.payload.user_name")
  - echo "$JOB_TRIGGERED_BY_NAME"
  - echo "message is $message"
  - if [ "$message" != $JOB_NAME ]; then return 1; fi
successTemplate: &successTemplate
  - shipctl put_resource_state $JOB_NAME response_url "$response_url"
  - shipctl put_resource_state $JOB_NAME user "$user"
  - result=$($RANDOM % 2)
  - shipctl put_resource_state $JOB_NAME result $result


#### row A, the first row
jobs:
  - name: A1
    type: runSh
    flags:
      - plinko
    dependencyMode: immediate
    runtime:
        nodePool: u14-dyna
    steps:
      - IN: A1Trig
      - IN: reset
      - TASK:
          script:
            - *mainTemplate

    on_success:
      script:
        - *successTemplate

  - name: A2
    type: runSh
    flags:
      - plinko
    dependencyMode: immediate
    runtime:
        nodePool: u14-dyna
    steps:
      - IN: A2Trig
      - IN: reset
      - TASK:
          script:
            - *mainTemplate
    on_success:
      script:
        - *successTemplate

  - name: A3
    type: runSh
    flags:
      - plinko
    dependencyMode: immediate
    runtime:
        nodePool: u14-dyna
    steps:
      - IN: A3Trig
      - IN: reset
      - TASK:
          script:
            - *mainTemplate
    on_success:
      script:
        - *successTemplate

  - name: A4
    type: runSh
    flags:
      - plinko
    dependencyMode: immediate
    runtime:
        nodePool: u14-dyna
    steps:
      - IN: A4Trig
      - IN: reset
      - TASK:
          script:
            - *mainTemplate
    on_success:
      script:
        - *successTemplate

  - name: A5
    type: runSh
    flags:
      - plinko
    dependencyMode: immediate
    runtime:
        nodePool: u14-dyna
    steps:
      - IN: A5Trig
      - IN: reset
      - TASK:
          script:
            - *mainTemplate
    on_success:
      script:
        - *successTemplate

  - name: A6
    type: runSh
    flags:
      - plinko
    dependencyMode: immediate
    runtime:
        nodePool: u14-dyna
    steps:
      - IN: A6Trig
      - IN: reset
      - TASK:
          script:
            - *mainTemplate
    on_success:
      script:
        - *successTemplate

  - name: A7
    type: runSh
    flags:
      - plinko
    dependencyMode: immediate
    runtime:
        nodePool: u14-dyna
    steps:
      - IN: A7Trig
      - IN: reset
      - TASK:
          script:
            - *mainTemplate
    on_success:
      script:
        - *successTemplate

  - name: A8
    type: runSh
    flags:
      - plinko
    dependencyMode: immediate
    runtime:
        nodePool: u14-dyna
    steps:
      - IN: A8Trig
      - IN: reset
      - TASK:
          script:
            - *mainTemplate
    on_success:
      script:
        - *successTemplate

  - name: A9
    type: runSh
    flags:
      - plinko
    dependencyMode: immediate
    runtime:
        nodePool: u14-dyna
    steps:
      - IN: A9Trig
      - IN: reset
      - TASK:
          script:
            - *mainTemplate
    on_success:
      script:
        - *successTemplate


#### triggering resources
resources:
  - name: A1Trig
    type: params
    versionTemplate:
      params:
        name: A1Trig

  - name: A2Trig
    type: params
    versionTemplate:
      params:
        name: A2Trig

  - name: A3Trig
    type: params
    versionTemplate:
      params:
        name: A3Trig

  - name: A4Trig
    type: params
    versionTemplate:
      params:
        name: A4Trig

  - name: A5Trig
    type: params
    versionTemplate:
      params:
        name: A5Trig

  - name: A6Trig
    type: params
    versionTemplate:
      params:
        name: A6Trig

  - name: A7Trig
    type: params
    versionTemplate:
      params:
        name: A7Trig

  - name: A8Trig
    type: params
    versionTemplate:
      params:
        name: A8Trig

  - name: A9Trig
    type: params
    versionTemplate:
      params:
        name: A9Trig