mainTemplate: &mainTemplate
  - if [ $JOB_TRIGGERED_BY_NAME == "reset" ]; then echo "resetting job to failed state"; return 1; fi

successTemplate: &successTemplate
  - result=$(($RANDOM % 2))
  - randomOut=${outs[$result]}
  - echo "randomly bouncing to $randomOut"
  - shipctl put_resource_state $randomOut response_url "$response_url"
  - shipctl put_resource_state $randomOut user "$user"

### row B, has 8 members

jobs:
  - name: B1
    type: runSh
    flags:
      - plinko
    dependencyMode: immediate
    runtime:
        nodePool: u14-dyna
    steps:
      - IN: B1Trig
      - IN: reset
      - TASK:
          script:
            - *mainTemplate
    on_success:
      script:
        - shipctl put_resource_state $JOB_NAME response_url "$response_url"
        - shipctl put_resource_state $JOB_NAME user "$user"
        - result=$($RANDOM % 2)
        - shipctl put_resource_state $JOB_NAME result=$result


  - name: B2
    type: runSh
    flags:
      - plinko
    dependencyMode: immediate
    runtime:
        nodePool: u14-dyna
    steps:
      - IN: B2Trig
      - IN: reset
      - TASK:
          script:
            - *mainTemplate
    on_success:
      script:
        - shipctl put_resource_state $JOB_NAME response_url "$response_url"
        - shipctl put_resource_state $JOB_NAME user "$user"
        - result=$($RANDOM % 2)
        - shipctl put_resource_state $JOB_NAME result=$result

  - name: B3
    type: runSh
    flags:
      - plinko
    dependencyMode: immediate
    runtime:
        nodePool: u14-dyna
    steps:
      - IN: B3Trig
      - IN: reset
      - TASK:
          script:
            - *mainTemplate
    on_success:
      script:
        - shipctl put_resource_state $JOB_NAME response_url "$response_url"
        - shipctl put_resource_state $JOB_NAME user "$user"
        - result=$($RANDOM % 2)
        - shipctl put_resource_state $JOB_NAME result=$result

  - name: B4
    type: runSh
    flags:
      - plinko
    dependencyMode: immediate
    runtime:
        nodePool: u14-dyna
    steps:
      - IN: B4Trig
      - IN: reset
      - TASK:
          script:
            - *mainTemplate
    on_success:
      script:
        - shipctl put_resource_state $JOB_NAME response_url "$response_url"
        - shipctl put_resource_state $JOB_NAME user "$user"
        - result=$($RANDOM % 2)
        - shipctl put_resource_state $JOB_NAME result=$result

  - name: B5
    type: runSh
    flags:
      - plinko
    dependencyMode: immediate
    runtime:
        nodePool: u14-dyna
    steps:
      - IN: B5Trig
      - IN: reset
      - TASK:
          script:
            - *mainTemplate
    on_success:
      script:
        - shipctl put_resource_state $JOB_NAME response_url "$response_url"
        - shipctl put_resource_state $JOB_NAME user "$user"
        - result=$($RANDOM % 2)
        - shipctl put_resource_state $JOB_NAME result=$result

  - name: B6
    type: runSh
    flags:
      - plinko
    dependencyMode: immediate
    runtime:
        nodePool: u14-dyna
    steps:
      - IN: B6Trig
      - IN: reset
      - TASK:
          script:
            - *mainTemplate
    on_success:
      script:
        - shipctl put_resource_state $JOB_NAME response_url "$response_url"
        - shipctl put_resource_state $JOB_NAME user "$user"
        - result=$($RANDOM % 2)
        - shipctl put_resource_state $JOB_NAME result=$result

  - name: B7
    type: runSh
    flags:
      - plinko
    dependencyMode: immediate
    runtime:
        nodePool: u14-dyna
    steps:
      - IN: B7Trig
      - IN: reset
      - TASK:
          script:
            - *mainTemplate
    on_success:
      script:
        - shipctl put_resource_state $JOB_NAME response_url "$response_url"
        - shipctl put_resource_state $JOB_NAME user "$user"
        - result=$($RANDOM % 2)
        - shipctl put_resource_state $JOB_NAME result=$result

  - name: B8
    type: runSh
    flags:
      - plinko
    dependencyMode: immediate
    runtime:
        nodePool: u14-dyna
    steps:
      - IN: B8Trig
      - IN: reset
      - TASK:
          script:
            - *mainTemplate
    on_success:
      script:
        - shipctl put_resource_state $JOB_NAME response_url "$response_url"
        - shipctl put_resource_state $JOB_NAME user "$user"
        - result=$($RANDOM % 2)
        - shipctl put_resource_state $JOB_NAME result=$result

#### triggering IN resources
resources:
  - name: B1Trig
    type: params
    versionTemplate:
      params:
        name: B1Trig

  - name: B2Trig
    type: params
    versionTemplate:
      params:
        name: B2Trig

  - name: B3Trig
    type: params
    versionTemplate:
      params:
        name: B3Trig

  - name: B4Trig
    type: params
    versionTemplate:
      params:
        name: A4Trig

  - name: B5Trig
    type: params
    versionTemplate:
      params:
        name: A5Trig

  - name: B6Trig
    type: params
    versionTemplate:
      params:
        name: A6Trig

  - name: B7Trig
    type: params
    versionTemplate:
      params:
        name: A7Trig

  - name: B8Trig
    type: params
    versionTemplate:
      params:
        name: A8Trig

  - name: B9Trig
    type: params
    versionTemplate:
      params:
        name: B9Trig