### commonly used in all rows
resources:
  - name: start
    type: webhook
    versionTemplate:
      webhookKey: startplinko
  - name: reset
    type: webhook
    versionTemplate:
      webhookKey: resetplinko

jobs:
  - name: start_job
    type: runSh
    flags:
      - plinko
    runtime:
      nodePool: u14-dyna
    steps:
      - IN: start
      - TASK:
          script:
            - HOOK_META=$(shipctl get_resource_meta $JOB_TRIGGERED_BY_NAME)
            - cat $HOOK_META/version.json | jq '.'
            - export response_url=$(shipctl get_json_value "$HOOK_META/version.json" "version.propertyBag.payload.response_url")
            - export message=$(shipctl get_json_value "$HOOK_META/version.json" "version.propertyBag.payload.text")
            - export user=$(shipctl get_json_value "$HOOK_META/version.json" "version.propertyBag.payload.user_name")
            - if [ -z "$message" ]; then echo "bad input $message"; return 1; fi
            - rand=$(($RANDOM % 9)) #0-8
            - let rand+=1 #1-9
            - if [ "$message" == "random" ]; then echo "randomly selected A$rand"; message="A$rand"; fi
            - outguy="$message"Trig
      - OUT: A1Trig
      - OUT: A2Trig
      - OUT: A3Trig
      - OUT: A4Trig
      - OUT: A5Trig
      - OUT: A6Trig
      - OUT: A7Trig
      - OUT: A8Trig
      - OUT: A9Trig
    on_success:
      script:
        - shipctl put_resource_state $outguy response_url "$response_url"
        - shipctl put_resource_state $outguy user "$user"